---
title: "Specifying Columns"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Specifying Columns}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
library(ggplot2)
library(emphatic)
hl_opt_global(dark_mode = FALSE)
```

```{r setup}
library(dplyr)
library(ggplot2)
library(emphatic)
hl_opt_global(dark_mode = FALSE)
```

```{r}
test_df <- head(mtcars, 10)
```



Select all cols
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue')
```

```{r}
test_df %>%
  hl('skyblue', cols = NULL)
```

```{r}
test_df %>%
  hl('skyblue', cols = .all)
```


Select cols by index
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue', cols = 2:5)
```

Select cols by name
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue', cols = c('mpg', 'gear'))
```

Select cols by rowname symbol
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue', cols = drat)
```

```{r}
test_df %>%
  hl('skyblue', cols = drat:am)
```


Select cols using `col_number()`
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue', cols = col_number() < 4)
```

Select cols using selectors like `tidyselect`
------------------------------------------------------------------------------

```{r}
test_df %>%
  hl('skyblue', cols = contains('a'))
```

```{r}
test_df %>%
  hl('skyblue', cols = ends_with('t'))
```


```{r}
test_df %>%
  hl('skyblue', cols = any_of(c('mpg', 'wt', 'age')))
```

